name: Kök Neden Analizi CI

on: [push]

jobs:
  # TEST 1: ubuntu-20.04 sanal makinesi çalışıyor mu? (Docker OLMADAN)
  test_runner:
    runs-on: ubuntu-20.04
    steps:
      - name: Runner'ı Test Et
        run: echo "Ubuntu 20.04 runner başarıyla çalıştı."

  # TEST 2: ubuntu-20.04 üzerinde Docker komutu çalışıyor mu?
  test_docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Docker'ı Test Et
        run: docker run hello-world
